name = "Air"
type = "cli"

[platform.linux]
checksum-file = "air_{version}_checksums.txt"
download-file = "air_{version}_linux_{arch}.tar.gz"

[platform.macos]
checksum-file = "air_{version}_checksums.txt"
download-file = "air_{version}_darwin_{arch}.tar.gz"

[install]
checksum-url = "https://github.com/air-verse/air/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/air-verse/air/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"

[install.exes.air]
exe-path = "air"
primary = true

[resolve]
git-url = "https://github.com/air-verse/air"
